# Generated by Django 5.2.4 on 2025-08-18 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_category_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='blog_videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog_video_thumbnails/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='blogs.blog')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
