# Generated by Django 5.2.4 on 2025-09-19 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogvideo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_views', to='blogs.blog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['blog', 'user'], name='blogs_blogv_blog_id_fc5647_idx'), models.Index(fields=['blog', 'ip_address'], name='blogs_blogv_blog_id_b9a600_idx'), models.Index(fields=['created_at'], name='blogs_blogv_created_7ed5e0_idx')],
                'unique_together': {('blog', 'ip_address'), ('blog', 'user')},
            },
        ),
    ]
