# Generated by Django 5.2.4 on 2025-09-19 05:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blogview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blogview',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='blogview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('blog', 'user'), name='unique_view_per_user_per_blog'),
        ),
        migrations.AddConstraint(
            model_name='blogview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('blog', 'ip_address'), name='unique_view_per_ip_per_blog'),
        ),
    ]
