# Generated by Django 5.2.4 on 2025-09-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_email_verified_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='token',
            field=models.CharField(default=None, max_length=8, unique=True),
        ),
    ]
