# Generated by Django 5.2.4 on 2025-08-30 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_generation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegeneration',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='imagegeneration',
            name='style',
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='analysis_type',
            field=models.CharField(choices=[('description', 'General Description'), ('detailed', 'Detailed Analysis'), ('caption', 'Caption'), ('ocr', 'Text Extraction (OCR)')], default='description', max_length=20),
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='generated_text',
            field=models.TextField(blank=True, help_text='AI-generated description of the image'),
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_images/'),
        ),
        migrations.AlterField(
            model_name='imagegeneration',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagegeneration',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of image to analyze (if not uploading file)'),
        ),
        migrations.AlterField(
            model_name='imagegeneration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imagegeneration',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
