# Generated by Django 5.2.4 on 2025-09-07 18:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing_style', models.CharField(choices=[('professional', 'Professional'), ('casual', 'Casual'), ('creative', 'Creative'), ('academic', 'Academic')], default='professional', max_length=50)),
                ('response_length', models.CharField(choices=[('short', 'Short & Concise'), ('medium', 'Medium'), ('long', 'Detailed')], default='medium', max_length=20)),
                ('include_references', models.BooleanField(default=True)),
                ('auto_suggest_topics', models.BooleanField(default=True)),
                ('context_awareness', models.BooleanField(default=True)),
                ('enable_suggestions', models.BooleanField(default=True)),
                ('proactive_assistance', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('context_type', models.CharField(choices=[('blog_writing', 'Blog Writing'), ('general', 'General Chat'), ('content_enhancement', 'Content Enhancement')], default='blog_writing', max_length=50)),
                ('context_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'User'), ('assistant', 'AI Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('text', 'Text Message'), ('suggestion', 'Content Suggestion'), ('generation', 'Generated Content'), ('enhancement', 'Content Enhancement'), ('system', 'System Message')], default='text', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('retrieved_documents', models.JSONField(blank=True, default=list)),
                ('context_used', models.TextField(blank=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_helpful', models.BooleanField(blank=True, null=True)),
                ('feedback_notes', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_assistant.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-updated_at'], name='chat_assist_user_id_46d395_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'context_type'], name='chat_assist_user_id_c401b7_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='chat_assist_session_db3978_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'message_type'], name='chat_assist_sender_48a2ab_idx'),
        ),
    ]
